CLASS zcljs_event_consumption DEFINITION
PUBLIC ABSTRACT FINAL
FOR EVENTS OF zcjs_r_currency.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCLJS_EVENT_CONSUMPTION IMPLEMENTATION.
ENDCLASS.
