CLASS zbp_i_rap_travel_0908 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_rap_travel_0908.
protected section.
private section.
ENDCLASS.



CLASS ZBP_I_RAP_TRAVEL_0908 IMPLEMENTATION.
ENDCLASS.
