CLASS zrap99_bp_traveltp_sol DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zrap99_r_traveltp_sol.
protected section.
private section.
ENDCLASS.



CLASS ZRAP99_BP_TRAVELTP_SOL IMPLEMENTATION.
ENDCLASS.
