CLASS LHC_DMOGEN2P DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEUUIDPOS FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DMOGen2P~CalculateUuidPos .
ENDCLASS.

CLASS LHC_DMOGEN2P IMPLEMENTATION.
  METHOD CALCULATEUUIDPOS.
  ENDMETHOD.
ENDCLASS.
