CLASS LHC_DMOGEN2S DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEUUIDSUBPOS FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DMOGen2S~CalculateUuidSubPos .
ENDCLASS.

CLASS LHC_DMOGEN2S IMPLEMENTATION.
  METHOD CALCULATEUUIDSUBPOS.
  ENDMETHOD.
ENDCLASS.
